//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hayvanat_Bahcesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calisan()
        {
            this.Ctelefons = new HashSet<Ctelefon>();
            this.Hayvans = new HashSet<Hayvan>();
            this.Bilets = new HashSet<Bilet>();
        }
    
        public int Cid { get; set; }
        public string Cad { get; set; }
        public string Csoyad { get; set; }
        public Nullable<int> Cmaas { get; set; }
        public string Ckidem { get; set; }
        public Nullable<int> HBid { get; set; }
    
        private HayvanatBahcesi HayvanatBahcesi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Ctelefon> Ctelefons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Hayvan> Hayvans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<Bilet> Bilets { get; set; }
    }
}
