//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hayvanat_Bahcesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ctelefon
    {
        public int Ctelefon1 { get; set; }
        public int Cid { get; set; }
    
        private Calisan Calisan { get; set; }
    }
}
