//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hayvanat_Bahcesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hayvan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hayvan()
        {
            this.HayvanDetays = new HashSet<HayvanDetay>();
        }
    
        public int Hid { get; set; }
        public string Hcins { get; set; }
        public Nullable<int> Hkafesno { get; set; }
        public Nullable<int> HdogumT { get; set; }
        public string Hhabitat { get; set; }
        public Nullable<int> Cid { get; set; }
        public Nullable<int> HBid { get; set; }
    
        private Calisan Calisan { get; set; }
        private HayvanatBahcesi HayvanatBahcesi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HayvanDetay> HayvanDetays { private get; set; }
    }
}
