//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hayvanat_Bahcesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HayvanDetay
    {
        public int HDid { get; set; }
        public int Hid { get; set; }
        public Nullable<int> HDboy { get; set; }
        public Nullable<int> HDgenislik { get; set; }
        public string HDdiyet { get; set; }
        public string HDcinsiyet { get; set; }
        public string HDbeslenme { get; set; }
    
        public virtual Hayvan Hayvan { get; set; }
    }
}
