//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hayvanat_Bahcesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HayvanatBahcesiEntities : DbContext
    {
        public HayvanatBahcesiEntities()
            : base("name=HayvanatBahcesiEntities")
        {
            Bilets = Set<Bilet>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Bilet> Bilets { get; set; }
        public virtual DbSet<Calisan> Calisans { get; set; }
        public virtual DbSet<Hayvan> Hayvans { get; set; }
        public virtual DbSet<HayvanatBahcesi> HayvanatBahcesis { get; set; }
        public virtual DbSet<HayvanDetay> HayvanDetays { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Ctelefon> Ctelefons { get; set; }
        public virtual DbSet<Mtelefon> Mtelefons { get; set; }
    }
}
